import 'package:equatable/equatable.dart';
import 'package:flutter/cupertino.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedUser {
  final List<UserModel> results;

  AutogeneratedUser({this.results});

  factory AutogeneratedUser.fromJson(Map<String, dynamic> json) {
    List<UserModel> temp = <UserModel>[];

    if (json['users'] != null) {
      json['users']?.forEach((v) {
        temp.add(UserModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedUser(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['users'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

@immutable
class UserModel extends Equatable {
  final String id;
  final String username;
  final String email;
  final String password;

  UserModel({
    @required this.id,
    this.username,
    this.email,
    this.password,
  });

  @override
  List<Object> get props => [id, username];

  factory UserModel.fromJson(Map<String, dynamic> json) {
    return UserModel(
      id: json['id'] as String,
      username: json['username'] as String,
      email: json['email'] as String,
      password: json['password'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['username'] = username;
    data['email'] = email;
    data['password'] = password;
    return data;
  }
}
