part 'api_const.dart';
part 'theme_const.dart';
part 'user_profile_const.dart';
part 'validators_const.dart';
part 'numbers_const.dart';

const String kAbout = 'About';
const String kSignout = 'Sign-out';
const String kUpdate = 'Update';
const String kConfirmAccount = 'confirm_account';
const String kProfileSetup = 'profile_setup';
const String kProfile = 'profile';
const String kInterest = 'interest';
const String kPasswordReset = 'password_reset';
const String kVerified = 'verified';
const String appName = 'Plug';
const String kSession = 'session';
const String kAuthStatus = 'auth_status';
const String kUserId = 'userId';
const String kToken = 'token';
const String kSuccess = 'success';
const String kCache = 'graphql_cache';
const String kHiveStore = 'hiveStore';
const String kRegister = 'register';
const String kLogin = 'login';
const String kReset = 'reset';
const String kVerify = 'verify';
const String kSubmit = 'submit';
const String kVerifyEmail = 'verifyEmail';
const String kVerifyEmailOrPhone = 'verifyEmailOrPhone';
const String kStoreVerificationCode = 'storeVerificationCode';
const String kContinue = 'continue';
const String kChooseGender = 'choose_gender';
const String kChooseProfession = 'choose_profession';
const String kLeave = 'Leave';
const String kUnsubscribe = 'Unsubscribe';
const String kSubscribe = 'Subscribe';
const String kDisplay = 'display';
const String kValue = 'value';
const String kSelectInterest = 'select_interest';
const String kImage = 'image';
const String kVideo = 'video';
const String kLike = 'like';
const String kDisLike = 'disLike';
const String kAppId = 'bw.co.pixel5tech.plug';
const String kNotifications = 'notifications';
const String kNotification = 'notification';
const String kJoin = 'join';
const String kMember = 'member';
const String kStandard = 'standard';
const String kPremium = 'premium';
const String kAdministrator = 'administrator';
const String kCommunity = 'community';
const String kCreated = 'created';
const String kUpdated = 'updated';
const String kUsername = 'username';

const List<String> kChoices = [kAbout, kLeave];

const kAnimationDuration = Duration(milliseconds: 200);
const defaultDuration = Duration(milliseconds: 250);

const String kPost = 'post';
const String kPosts = 'posts';
const double kMinsToMillis = 0.00001667;
