import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:jica/src/core/models/device_battery.dart';
import 'package:jica/src/services/bloc/base_graphql_bloc.dart';
import 'package:jica/src/services/bloc/device_bloc.dart';
import 'package:jica/src/utils/debugBro.dart';
import 'package:jica/src/utils/dialogs.dart';

class BatteryDeviceInformation extends StatefulWidget {
  final String deviceID;

  const BatteryDeviceInformation({Key key, this.deviceID}) : super(key: key);

  @override
  State<BatteryDeviceInformation> createState() =>
      _BatteryDeviceInformationState();
}

class _BatteryDeviceInformationState extends State<BatteryDeviceInformation> {
  List<DeviceBattery> batteries = [];
  @override
  void didChangeDependencies() {
    context.read<DeviceBloc>()..getBatteryInfo(widget.deviceID);
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<DeviceBloc, GraphqlState>(
      builder: (BuildContext context, GraphqlState state) {
        return SingleChildScrollView(
          child: DataTable(
            columnSpacing: 10,
            columns: const <DataColumn>[
              DataColumn(
                label: Text(
                  'Voltage',
                  style: TextStyle(
                      fontStyle: FontStyle.italic, fontWeight: FontWeight.bold),
                ),
              ),
              DataColumn(
                label: Text(
                  'stepNum',
                  style: TextStyle(
                      fontStyle: FontStyle.italic, fontWeight: FontWeight.bold),
                ),
              ),
              DataColumn(
                label: Text(
                  'signalStrength',
                  style: TextStyle(
                      fontStyle: FontStyle.italic, fontWeight: FontWeight.bold),
                ),
              ),
              DataColumn(
                label: Text(
                  'Timestamp',
                  style: TextStyle(
                      fontStyle: FontStyle.italic, fontWeight: FontWeight.bold),
                ),
              ),
            ],
            rows: <DataRow>[
              for (var battery in batteries)
                DataRow(
                  cells: <DataCell>[
                    DataCell(Text('${battery.batteryVoltage}')),
                    DataCell(Text('${battery.stepNum}')),
                    DataCell(Text('${battery.signalStrength}')),
                    DataCell(Text('${battery.timestamp}')),
                  ],
                )
            ],
          ),
        );
      },
      listener: (context, state) {
        if (state is GraphqlLoadedState) {
          Dialogs.closeLoadingDialog(context);
          batteries = AutogeneratedDeviceBattery.fromJson({
            'results': state.data['getDeviceBattery']['deviceBatteries']
          }).results;

          batteries = batteries.reversed.toList();
        }

        if (state is GraphqlErrorState) {
          logger.e(state.error);
        }

        if (state is GraphqlLoadingState) {
          Dialogs.showLoadingDialog(context,
              message: 'loading battery info...');
        }
      },
    );
  }
}
