import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:jica/src/core/models/device_health.dart';
import 'package:jica/src/services/bloc/base_graphql_bloc.dart';
import 'package:jica/src/services/bloc/device_bloc.dart';
import 'package:jica/src/utils/debugBro.dart';
import 'package:jica/src/utils/dialogs.dart';

class HealthDeviceInformation extends StatefulWidget {
  final String deviceID;

  const HealthDeviceInformation({Key key, this.deviceID}) : super(key: key);

  @override
  _DeviceInformationState createState() => _DeviceInformationState();
}

class _DeviceInformationState extends State<HealthDeviceInformation> {
  List<DeviceHealth> healths = [];

  @override
  void didChangeDependencies() {
    context.read<DeviceBloc>()..getHealthInfo(widget.deviceID);
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<DeviceBloc, GraphqlState>(
      builder: (BuildContext context, GraphqlState state) {
        return SingleChildScrollView(
          child: DataTable(
            columnSpacing: 10,
            columns: const <DataColumn>[
              DataColumn(
                label: Text(
                  'bpHigh',
                  style: TextStyle(fontStyle: FontStyle.italic),
                ),
              ),
              DataColumn(
                label: Text(
                  'bpLow',
                  style: TextStyle(fontStyle: FontStyle.italic),
                ),
              ),
              DataColumn(
                label: Text(
                  'heartRate',
                  style: TextStyle(fontStyle: FontStyle.italic),
                ),
              ),
              DataColumn(
                label: Text(
                  'timestamp',
                  style: TextStyle(fontStyle: FontStyle.italic),
                ),
              ),
            ],
            rows: <DataRow>[
              for (var health in healths)
                DataRow(
                  cells: <DataCell>[
                    DataCell(Text('${health.bpHigh}')),
                    DataCell(Text('${health.bpLow}')),
                    DataCell(Text('${health.heartRate}')),
                    DataCell(Text('${health.timestamp}')),
                  ],
                )
            ],
          ),
        );
      },
      listener: (context, state) {
        if (state is GraphqlLoadedState) {
          Dialogs.closeLoadingDialog(context);
          healths = AutogeneratedDeviceHealth.fromJson(
                  {'results': state.data['getDeviceHealth']['deviceHealth']})
              .results;
          healths = healths.reversed.toList();
        }

        if (state is GraphqlErrorState) {
          logger.e(state.error);
        }

        if (state is GraphqlLoadingState) {
          Dialogs.showLoadingDialog(context, message: 'loading health info...');
        }
      },
    );
  }
}
