import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:jica/src/core/models/device_temperature.dart';
import 'package:jica/src/services/bloc/base_graphql_bloc.dart';
import 'package:jica/src/services/bloc/device_bloc.dart';
import 'package:jica/src/utils/debugBro.dart';
import 'package:jica/src/utils/dialogs.dart';

class DeviceTemperatureInformation extends StatefulWidget {
  final String deviceID;

  const DeviceTemperatureInformation({Key key, this.deviceID})
      : super(key: key);

  @override
  _DeviceInformationState createState() => _DeviceInformationState();
}

class _DeviceInformationState extends State<DeviceTemperatureInformation> {
  List<DeviceTemperature> temperatures = [];

  @override
  void didChangeDependencies() {
    context.read<DeviceBloc>()..getTemperatureInfo(widget.deviceID);
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<DeviceBloc, GraphqlState>(
      builder: (BuildContext context, GraphqlState state) {
        return SingleChildScrollView(
          child: DataTable(
            columnSpacing: 10,
            columns: const <DataColumn>[
              DataColumn(
                label: Text(
                  'skinTemp',
                  style: TextStyle(fontStyle: FontStyle.italic),
                ),
              ),
              DataColumn(
                label: Text(
                  'bodyTemp',
                  style: TextStyle(fontStyle: FontStyle.italic),
                ),
              ),
              DataColumn(
                label: Text(
                  'timestamp',
                  style: TextStyle(fontStyle: FontStyle.italic),
                ),
              ),
            ],
            rows: <DataRow>[
              for (DeviceTemperature temperature in temperatures)
                DataRow(
                  cells: <DataCell>[
                    DataCell(Text('${temperature.skinTemp}')),
                    DataCell(Text('${temperature.bodyTemp}')),
                    DataCell(Text('${temperature.timestamp}')),
                  ],
                )
            ],
          ),
        );
      },
      listener: (context, state) {
        if (state is GraphqlLoadedState) {
          Dialogs.closeLoadingDialog(context);
          temperatures = AutogeneratedDeviceTemperature.fromJson(
                  {'results': state.data['getDeviceTemperature']['deviceTemp']})
              .results;
          temperatures = temperatures.reversed.toList();
        }

        if (state is GraphqlErrorState) {
          logger.e(state.error);
        }

        if (state is GraphqlLoadingState) {
          Dialogs.showLoadingDialog(context,
              message: 'loading device temperature info...');
        }
      },
    );
  }
}
